mapping: support for False additionalProperties
inveniosoftware/domapping pull request #20
Opened 2016-09-12 14:53 UTC by PXke

* Handle the case where additionalProperties is False.

Signed-off-by: Guillaume Lastecoueres <guillaume@tind.io>

2016-09-12 14:57 UTC, PXke commented
All is green :)

2016-09-12 15:01 UTC, PXke commented
The reason why I added it :
https://spacetelescope.github.io/understanding-json-schema/reference/object.html#properties

2016-09-13 09:31 UTC, jirikuncar commented on domapping/mapping.py
> +        Get the values associated to a specific key in nested dicts.
Please start the docstring on the same line after `"""`.

```python
"""Get ...
```

2016-09-13 09:31 UTC, jirikuncar commented on domapping/mapping.py
> +        :return: A list containing the value associated to Key.
`s/Key/key/`

2016-09-13 09:32 UTC, jirikuncar commented on domapping/mapping.py
> +        :param key: Key to look value for. If None, returns all values.
```python
if ``None``, it returns ...
```

2016-09-13 09:38 UTC, jirikuncar commented on domapping/mapping.py
> +    def dict_search_and_retrieve(d, key=None):
If I understand well you are trying to recursively find all values under the `key`. Consider yielding the values so the `any` function can evaluate to `True` early.

Try to find some descriptive name for the function (e.g. `iter_all_values_from_dict(data, key)`) and add some tests.

2016-09-13 09:40 UTC, jirikuncar commented
@PXke use topical branches when you create a PR.

2016-09-15 11:42 UTC, jirikuncar requested changes
Please refactor the recursive key extraction from a dict. Thanks

## 

see https://github.com/inveniosoftware/domapping/pull/20/files#r78526840

2016-10-11 11:19 UTC, closed without merging